name: CLI CI

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/cli-ci.yml
      - cli/**
      - deployment-core/**
      - mise.toml
  pull_request:
    paths:
      - .github/workflows/cli-ci.yml
      - cli/**
      - deployment-core/**
      - mise.toml

permissions:
  contents: read

defaults:
  run:
    working-directory: cli

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install: true
          working_directory: cli
      - run: mise run test
