name: Deployment Core CI

on:
  push:
    branches: [master]
    paths:
      - .github/workflows/deployment-core-ci.yml
      - deployment-core/**
      - mise.toml
  pull_request:
    paths:
      - .github/workflows/deployment-core-ci.yml
      - deployment-core/**
      - mise.toml

permissions:
  contents: read

defaults:
  run:
    working-directory: deployment-core

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
        with:
          install: true
          working_directory: deployment-core
      - run: mise run test
